before:
  hooks:
    - go mod download
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  ignore:
      - goarch: 386
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  name: playback
  github:
    owner: pburakov
    name: homebrew-io
  commit_author:
    name: Paul Burakov
    email: pburakov@gmail.com
  folder: Formula
